---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv1

spec: 
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  awsElasticBlockStore:
    volumeID: vol-04a8409861d48f281
    fsType: ext4

